#pragma once
#include "pebble-gbc-graphics-advanced/pebble-gbc-graphics-advanced.h"

// Debug
#define DEBUG_PATHS false
#define DEBUG_PATH_CHOICE 3
#define DEBUG_SCORES false

// Game info
#define NUM_TILE_TYPES 32
#define MAP_EDITOR_NUM_TILES 2
#define MAX_PLAYERS 4
#define USERNAME_MAX_LEN 11
#define FRAMERATE 8
#define FRAME_DURATION (1000 / FRAMERATE)
// Paths
#define SCORE_NULL -100
#define SCORE_WALL -1
#define SCORE_ROCK -1
#define SCORE_BLOCKING_THRESHOLD 0
#define SCORE_DEATH 0
#define SCORE_BOMB 1
#define SCORE_SAFE_THRESHOLD 20
#define SCORE_SAFE 21
#define SCORE_ITEM 22
#define SCORE_PATH_FAIL -1
#define SCORE_PATH_WALL -1
#define SCORE_PATH_END 0
#define SCORE_PATH_NONE 1
#define SCORE_PATH_ROCK 2
#define PATH_MAX_LEN 15
#define NO_OTHER_PLAYERS -1
#define CPU_START_TIMER_DELAY (FRAMERATE * 3)
#define CPU_TIMER_DELAY PLAYER_WALK_FRAME_COUNT
#define CPU_SLOW_TIMER_DELAY (CPU_TIMER_DELAY * 2)
#define CPU_TIMER_WAIT_ODDS 8
#define CPU_TIMER_WAIT_RANGE 8
#define CPU_SLOW_TIMER_WAIT_RANGE (CPU_TIMER_WAIT_RANGE * 2)

// Graphics
#define NUM_VRAMS 2
#define NUM_BACKGROUNDS 1
#define BACKGROUND_VRAM 0
#define PLAYER_VRAM 1
#define SQUARE_SIZE 16
// - Background
#define BLOCK_WIDTH 2
#define BLOCK_HEIGHT 2
#define BLOCK_SIZE (BLOCK_WIDTH * BLOCK_HEIGHT)
#define SCREEN_BLOCK_WIDTH 11
#define SCREEN_BLOCK_HEIGHT 9
#define SCREEN_BLOCK_SIZE (SCREEN_BLOCK_WIDTH * SCREEN_BLOCK_HEIGHT)
#define SCREEN_TILE_WIDTH (SCREEN_BLOCK_WIDTH * BLOCK_WIDTH)
#define SCREEN_TILE_HEIGHT (SCREEN_BLOCK_HEIGHT * BLOCK_HEIGHT)
#define SCREEN_PIXEL_WIDTH (SCREEN_TILE_WIDTH * GBC_TILE_WIDTH)
#define SCREEN_PIXEL_HEIGHT (SCREEN_TILE_HEIGHT * GBC_TILE_HEIGHT)
#if defined(PBL_PLATFORM_CHALK)
    #define SCREEN_BOUNDS GRect(2, 26, SCREEN_PIXEL_WIDTH, SCREEN_PIXEL_HEIGHT)
    #define SCREEN_OFFSET GPoint(0, 0)
#elif defined(PBL_PLATFORM_EMERY)
    #define SCREEN_BOUNDS GRect(12, 50, SCREEN_PIXEL_WIDTH, SCREEN_PIXEL_HEIGHT)
    #define SCREEN_OFFSET GPoint(0, 0)
#elif defined(PBL_PLATFORM_GABBRO)
    #define SCREEN_BOUNDS GRect(42, 66, SCREEN_PIXEL_WIDTH, SCREEN_PIXEL_HEIGHT)
    #define SCREEN_OFFSET GPoint(0, 0)
#else
    #define SCREEN_BOUNDS GRect(0, 20, SCREEN_PIXEL_WIDTH, SCREEN_PIXEL_HEIGHT)
    #define SCREEN_OFFSET GPoint(16, 0)
#endif
#define BACKGROUND_NUM_TILES (NUM_TILE_TYPES * BLOCK_SIZE)
// - Players
#define PLAYER_SPRITE_WIDTH 2
#define PLAYER_SPRITE_HEIGHT 3
#define PLAYER_SPRITE_SIZE (PLAYER_SPRITE_WIDTH * PLAYER_SPRITE_HEIGHT)
#define PLAYER_NUM_SPRITES 9
#define PLAYER_NUM_TILES (PLAYER_NUM_SPRITES * PLAYER_SPRITE_SIZE)
#define PLAYER_SPRITE_OFFSET_X 0
#define PLAYER_SPRITE_OFFSET_Y -8
#define PLAYER_STEP_SIZE 16
#define PLAYER_SUB_STEP_SIZE 4
#define PLAYER_WALK_FRAME_COUNT 4
#define SPAWN_INVULN_FRAMES 0
#define PLAYER_DEATH_FRAMES (2 * FRAMERATE)
#define PLAYER_FADE_START (1 * FRAMERATE)
extern const int16_t PLAYER_SPAWNS[MAX_PLAYERS][2];
// - Bombs
#define STARTING_BOMBS 1
#define BOMB_TICK_LIFETIME (7 * FRAMERATE)
#define BOMB_COUNTDOWN_START (3 * FRAMERATE)
#define BOMB_COUNT_FRAMES 3
#define MAX_BOMBS_PER_PLAYER 5
#define MAX_BOMBS_PER_GAME (MAX_BOMBS_PER_PLAYER * MAX_PLAYERS)
#define NO_BOMB_FOUND -1
// - Explosions
#define STARTING_EXPL_RADIUS 1
#define EXPL_TICK_LIFETIME (1.5 * FRAMERATE)
#define EXPL_NUM_SQUARES 9
#define MAX_EXPLOSIONS_PER_GAME ((MAX_BOMBS_PER_PLAYER + 1) * MAX_PLAYERS)
// - Rock
#define ROCK_TICK_LIFETIME EXPL_TICK_LIFETIME
#define ROCK_FADE_START (1 * FRAMERATE)
#define MAX_ROCKS_PER_GAME (SCREEN_BLOCK_SIZE / 2)
// - Item
#define ITEM_TICK_LIFETIME EXPL_TICK_LIFETIME
#define ITEM_FADE_START (1 * FRAMERATE)
#define MAX_ITEMS_PER_GAME (SCREEN_BLOCK_SIZE / 2)
#define NUM_ITEMS 4 // Exclude power
#define ITEM_SPAWN_RANGE (NUM_ITEMS * 3)
#define ITEM_SHIELD_INVULN_FRAMES (20 * FRAMERATE)

// Misc
#define NUM_DIRS 4
const int8_t X_Y_DIRS[NUM_DIRS+1][2];
const int8_t X_Y_MULTS[NUM_DIRS][2];
const uint8_t PATH_ORDERS[NUM_DIRS][NUM_DIRS];

// Maps
#define NUM_MAPS 3
#define START_MAP RESOURCE_ID_MAP1